---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinskubernetes-deployment
spec:
  selector:
    matchLabels:
      app: devops-automation
  replicas: 2
  template:
    metadata:
      labels:
        app: devops-automation
    spec:
      containers:
        - name: devopsautomation-container
          image: ahteeniv/devopsautomation # Replace with your Docker image name and tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkinskubernetes-service
spec:
  selector:
    app: devops-automation
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
